In [1]:
vishal=18.0

In [2]:
Flynn=14.0

In [3]:
print(vishal>10 and Flynn<18)

True


In [4]:
print(vishal <14 or Flynn>17)

False


In [5]:
print(vishal*2<Flynn*3)

True


In [6]:
not True

False

In [7]:
not vishal<20

False

In [9]:
import numpy as np

In [10]:
swarna_marks=np.array([18.0,20.0,10.75,9.50])

In [11]:
jay_marks=np.array([14.0,24.0,14.25,9.0])

In [16]:
np.logical_and(swarna_marks<11,jay_marks<11)

array([False, False, False,  True])

In [14]:
np.logical_or(swarna_marks,jay_marks)

array([ True,  True,  True,  True])

In [15]:
np.logical_or(swarna_marks>18.5,jay_marks<10)

array([False,  True, False,  True])